name: MOTOR HIL Test Suite

on:
  push:
    branches: [ main ]

jobs:
  test_hardware:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files (Debug)
        run: ls -la 

      - name: Run Hardware-in-the-Loop Diagnostics
        run: |
          # 1. Activate your local environment
          source /home/syki/Desktop/canpinnmonitor/venv/bin/activate
          
          # 2. Run the CORRECTly named file
          pytest test_motor_hil.py -v -s